version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      # Cache for HuggingFace models (persist between runs)
      - hf-cache:/data/hf-cache
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  hf-cache:
